### ISSUE TITLE
English version of published paper would be very useful (even if machine translated)

### ISSUE THREAD

**Issue by axsaucedo** [KoBeWi/The-Soulhunter#1]
It would be great to have an English version of the published paper - unfortunately Google translate has a limit of 5000 characters, and realistically it doesn't perform well in the more technical topics, and could be really useful as accompanying information for the repo

**Comment by KoBeWi** [comment]
> Google translate has a limit of 5000 characters

You can translate the text in parts.

Well, maybe I could Google-Translate the paper myself and link the English version. I'm not going to do a proper non-machine translation though xd

**Comment by axsaucedo** [comment]
My bad, by machine translation I did mean just through any translator, not running it through some ML system. The raw text / latex that would also be quite helpful, as the copy paste of the PDF is not ideal. However if you could do a google translate of the document, that would be fantastic and very much appreciated @KoBeWi

**Comment by KoBeWi** [comment]
Ok, added in 0d81ac3271eeca4ca3aad53763f88d8106139ee6. I translated the LaTeX source using Google Translate and compiled a new PDF. Hope it's readable.

Also you can report any document errors, like broken markdown leftovers, missing references etc.
